# Generated by Django 5.0.6 on 2024-06-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_groups', models.JSONField()),
                ('warehouse', models.CharField(max_length=50)),
                ('num_prices', models.IntegerField()),
                ('coefficients', models.JSONField()),
            ],
        ),
    ]
