# Generated by Django 5.0.6 on 2024-06-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_list_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='coefficients',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
