# Generated by Django 5.0.6 on 2024-07-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price_list_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
