# Generated by Django 5.0.6 on 2024-06-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_list_app', '0002_alter_configuration_coefficients'),
    ]

    operations = [
        migrations.CreateModel(
            name='NomenclatureMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10, unique=True)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PanelMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20, unique=True)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
    ]
