# Generated by Django 5.0.6 on 2024-07-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price_list_app", "0002_configuration_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configuration",
            name="name",
        ),
        migrations.AddField(
            model_name="pricelabel",
            name="coefficient_1",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="pricelabel",
            name="coefficient_2",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="pricelabel",
            name="coefficient_3",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="pricelabel",
            name="coefficient_4",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="pricelabel",
            name="operation_1",
            field=models.CharField(
                choices=[("*", "Multiplication"), ("+", "Addition")],
                default="*",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="pricelabel",
            name="operation_2",
            field=models.CharField(
                choices=[("*", "Multiplication"), ("+", "Addition")],
                default="*",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="pricelabel",
            name="operation_3",
            field=models.CharField(
                choices=[("*", "Multiplication"), ("+", "Addition")],
                default="*",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="pricelabel",
            name="operation_4",
            field=models.CharField(
                choices=[("*", "Multiplication"), ("+", "Addition")],
                default="*",
                max_length=1,
            ),
        ),
    ]
