# Generated by Django 5.0.6 on 2024-07-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "price_list_app",
            "0003_remove_configuration_name_pricelabel_coefficient_1_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="name",
            field=models.CharField(default="Unnamed Configuration", max_length=100),
        ),
    ]
