# Generated by Django 5.0.6 on 2024-07-10 11:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price_list_app", "0004_configuration_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="configuration",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="configuration",
            unique_together={("user", "name")},
        ),
    ]
