# Generated by Django 5.0.6 on 2024-06-29 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_list_app', '0005_alter_configuration_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='configuration',
            unique_together=set(),
        ),
    ]
