# Generated by Django 5.0.6 on 2024-07-10 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("price_list_app", "0005_alter_configuration_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="configuration",
            unique_together=set(),
        ),
    ]
