# Generated by Django 5.0.6 on 2024-07-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price_list_app", "0006_alter_configuration_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="select_all_brands",
            field=models.BooleanField(default=False),
        ),
    ]
