# Generated by Django 5.0.6 on 2024-06-29 07:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_list_app', '0006_alter_configuration_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='configuration',
            unique_together={('user', 'warehouse', 'selected_groups', 'num_prices')},
        ),
    ]
