# Generated by Django 5.0.6 on 2024-06-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_list_app', '0008_alter_configuration_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
