# Generated by Django 5.0.6 on 2024-07-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price_list_app", "0008_promotion"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="filters",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
