# Generated by Django 5.0.6 on 2024-07-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price_list_app", "0009_configuration_created_configuration_updated"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
