# Generated by Django 5.0.6 on 2024-07-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price_list_app", "0010_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="selected_brands",
            field=models.JSONField(default=list),
        ),
    ]
