# Generated by Django 5.0.6 on 2024-07-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price_list_app", "0012_backgroundimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="backgroundimage",
            name="image",
        ),
        migrations.AddField(
            model_name="backgroundimage",
            name="content_image",
            field=models.ImageField(
                default="backgrounds/default_content.jpg",
                upload_to="backgrounds/content/",
            ),
        ),
        migrations.AddField(
            model_name="backgroundimage",
            name="toc_image",
            field=models.ImageField(
                default="backgrounds/default_toc.jpg", upload_to="backgrounds/toc/"
            ),
        ),
    ]
